### ISSUE TITLE
wrangler: not found

### ISSUE THREAD

**Issue by techniq** [AdrianGonz97/cf-pages-action#17]
Hey @AdrianGonz97 👋, first awesome project, thanks for making it (and fixing the [shortcomings](https://github.com/techniq/svelte-ux/issues/278) of the official integration)!

We recently switched LayerChart and Svelte UX deployments to use this action (thanks @shyakadavis) and it's been working great until this afternoon when I [updated](https://github.com/techniq/svelte-ux/commit/6bcaf48e2349dbb7ed6f2dc1d4854f2080d16739) to Node 20.x (dropping 18.x) and [bumped](https://github.com/techniq/svelte-ux/commit/8f0292d157a62ae5bca8b6a2537c1586001fa994) some package.json dependencies. 

Now the job is giving `wrangler: not found` from what looks to be `npx wrangler@3 pages deploy ...` which doesn't make sense to me.

![image](https://github.com/user-attachments/assets/c9bb9335-9233-4ae9-8b7b-bbc9fd1f91ac)

Any thoughts of something I'm overlooking.  Maybe it's just an npm hiccup or something, but it's failed for both Svelte UX and LayerChart after making the same changes.

Thanks for any help.

**Comment by AdrianGonz97** [comment]
Hey! So I've noticed this issue in the past when using dependencies (such as `@sveltejs/adapter-cloudflare`) where `wrangler` is a transitive dependency and `npx` gets all confused for some reason. Not exactly sure why it behaves like that.

The fix is to install `wrangler` to the project as a `devDependency`. If you're in a monorepo, install it to the root.

**Comment by techniq** [comment]
> Hey! So I've noticed this issue in the past when using dependencies (such as `@sveltejs/adapter-cloudflare`) where `wrangler` is a transitive dependency and `npx` gets all confused for some reason. Not exactly sure why it behaves like that.
> 
> The fix is to install `wrangler` to the project as a `devDependency`. If you're in a monorepo, install it to the root.

Thanks for the quick reply, and great idea.  Giving that a go and will report back.

**Comment by techniq** [comment]
That did the trick, thanks @AdrianGonz97!

![image](https://github.com/user-attachments/assets/e3c914f6-ddc1-4123-a778-bbcbd6bbcf9c)
