### ISSUE TITLE
PRs with `main` branch

### ISSUE THREAD

**Issue by techniq** [AdrianGonz97/cf-pages-action#18]
I've noticed if a [PR](https://github.com/techniq/svelte-ux/pull/464) uses a `main` branch on their fork it is causing Cloudflare to treat this as a production deployment even though only the  `build-preview.yml` / `deploy-preview.yml` [workflows](https://github.com/techniq/svelte-ux/tree/main/.github/workflows) are running (i.e. not `deply-prod.yml`)

![image](https://github.com/user-attachments/assets/0b96c7f6-c1c1-45ba-9b0e-f60596ba4e3f)

![image](https://github.com/user-attachments/assets/5bc91758-7beb-46cd-9b4b-d767d842f7d8)

This could very well be a misconfiguration on my side (within Cloudflare, etc), but I couldn't identify any way to qualify source repo (only branch).

![image](https://github.com/user-attachments/assets/958de4ad-3800-4f81-a158-20df0d563094)

I could turn off automatic deployments of the main branch, but I would rather not if possible.

I know @huntabyte is using a similar workflows with [bits-ui](https://github.com/huntabyte/bits-ui/tree/main/.github/workflows) so this could affect that repo as well unless I'm overlooking something on my end.

cc: @shyakadavis

**Comment by AdrianGonz97** [comment]
Thanks for the report! 

This was actually a bug that was originally fixed in #15, but a regression in #16 reintroduced the issue. #19 should resolve this now.
