### ISSUE TITLE
Can't figure out how to push to production :-(

### ISSUE THREAD

**Issue by wmertens** [AdrianGonz97/cf-pages-action#22]
The building from other-repo PRs works great, but when we merge into main and the deploy gets triggered, it doesn't send it to CF production. What am I missing?

Here's the run that should have been a production push: https://github.com/QwikDev/qwik/actions/runs/10910473101

**Comment by AdrianGonz97** [comment]
Is the production branch for the project set to `main` on Cloudflare Pages?

You can view this by following these steps:
**Workers & Pages** > **Select your pages project** > **Settings** > **Builds & deployments**

or by going here (replacing the `<>` with your account and project information):
```
https://dash.cloudflare.com/<ACCOUNT_ID>/pages/view/<PROJECT_NAME>/settings/builds-deployments
```

---

If it's already set to `main`, then I'll dedicate some time tomorrow looking into it since the detected settings in that job indicates that it _should_ be pushing to production.

**Comment by wmertens** [comment]
yes it's `main`. Looking at #19 I think it's because it doesn't push to production on workflow runs, and we only do workflow runs.

I'm trying to work around it in https://github.com/QwikDev/qwik/pull/6889/files#diff-87e860af4b9db6c503ed680b6edb6333c6f8d7659f7d1a779a2487466bbc50f6R49, but maybe the logic should just be that it is allowed to be a workflow run if it's not a PR run

**Comment by AdrianGonz97** [comment]
great catch, thanks! 

I've created a PR to address this: #23 

Feel free to try it out by referencing the branch:
```
uses: AdrianGonz97/refined-cf-pages-action@fix/deploy-prod-on-workflow_run
```

**Comment by wmertens** [comment]
@AdrianGonz97 it failed :( It tried to comment on the PR even though it was a merge

https://github.com/QwikDev/qwik/actions/runs/10940788497/job/30373962994

**Comment by AdrianGonz97** [comment]
@wmertens thanks for the update! I just pushed another update to the branch to address that.

To test, you can simply re-run the job of this workflow:
https://github.com/QwikDev/qwik/actions/runs/10940788497/job/30373962994

**Comment by wmertens** [comment]
Thank you! 

This time the run worked but it didn't get deployed to production :(

https://github.com/QwikDev/qwik/actions/runs/10940788497/job/30386945147

**Comment by AdrianGonz97** [comment]
hmm, it looks like the changes were deployed to prod: https://qwik.dev/docs/advanced/containers/

...unless these were published in a separate deployment?

do the deployment logs on cloudflare pages say otherwise for you? are they being deployed as previews instead?

**Comment by wmertens** [comment]
oh sorry - either I checked too soon or my phone cached too hard :sweat_smile: 

Deployment to prod looks fine, thanks! :raised_hands:

**Comment by AdrianGonz97** [comment]
@wmertens great! I'll cut a new release shortly. You'll also need to update the reference so it's no longer pointing to the `fix/deploy-prod-on-workflow_run` branch. I'll keep the branch around for a few days before deleting it.
